services:

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.weird
    ports:
      - "3000:3000"
    volumes:
      - db-data:/usr/src/app
    networks:
      - gpx-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: production
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - gpx-network
    restart: unless-stopped

  e2e-tests:
    build:
      context: .
      dockerfile: Dockerfile.test.frontend
      target: tester
    depends_on:
      - frontend
      - backend
    #command: ["npm", "run", "test:e2e"]
    ports:
      - "9323:9323"
    # Mount the test results directory to the host
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
    networks:
      - gpx-network

volumes:
  db-data:

networks:
  gpx-network:
    driver: bridge