services:

  backend:
    build: 
      context: ../backend
      dockerfile: ../deployment/backend.Dockerfile.weird
    ports:
      - "3000:3000"
    volumes:
      - db-data:/usr/src/app
    networks:
      - gpx-network
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: ../deployment/frontend.Dockerfile
      target: production
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - gpx-network
    restart: unless-stopped

  e2e-tests:
    build:
      context: ../frontend
      dockerfile: ../deployment/frontend.Dockerfile.test
      target: tester
    depends_on:
      - frontend
      - backend
    #command: ["npm", "run", "test:e2e"]
    ports:
      - "9323:9323"
    # Mount the test results directory to the host
    volumes:
      - ../frontend/playwright-report:/app/playwright-report
      - ../frontend/test-results:/app/test-results
    networks:
      - gpx-network

volumes:
  db-data:

networks:
  gpx-network:
    driver: bridge