services:
  backend:
    build: 
      context: ../backend
      dockerfile: ../deployment/backend.Dockerfile.weird
    ports:
      - "3000:3000"
    volumes:
      - db-data:/usr/src/app
    networks:
      - gpx-network
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: ../deployment/frontend.Dockerfile
      target: production
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - gpx-network
    restart: unless-stopped

volumes:
  db-data:

networks:
  gpx-network:
    driver: bridge
